### ISSUE TITLE
Display Images in greadme service

### ISSUE THREAD

**Issue by wikimatze** [aheckmann/greadme#18]
Hey,

we want do display a image with `![img jo](images/img.png)` and the image is there. The generated HTML can display has the correct link `<img src="images/img.png"` but the picture will be displayed, see the following picture:

![greadme_issue](https://cloud.githubusercontent.com/assets/264708/5935590/b9299b36-a6dc-11e4-85cd-f6fe462a474e.png)

Going to the picture URL gives us the image as a funny hex string (or any other format).

![greadme_funny_picture](https://cloud.githubusercontent.com/assets/264708/5935592/bdb08610-a6dc-11e4-95fa-0880bc039ba4.png)

Thanks for taking care of this issue and thanks for this awesome tool, I really like it.

Best 

Matthias

**Comment by aheckmann** [comment]
should work in 1.0.0

**Comment by wikimatze** [comment]
Cool, thanks, will check it out tomorrow and then close the ticket.
